#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "piped"
name = "Piped"

description.en = "An open-source alternative frontend for YouTube which is efficient by design."

version = "2025.06.26~ynh2"

maintainers = [ "orhtej2" ]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://docs.piped.video/"
demo = "https://piped.video/"
admindoc = "https://docs.piped.video/docs/"

code = "https://github.com/TeamPiped/Piped"

[integration]
yunohost = '>= 11.2'
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/TeamPiped/Piped/archive/25a3b7ca0f5de3ec12c49988ca455dae5226055d.tar.gz"
        sha256 = "23674b1d521c21afe61c2604b89f3f8d097a02c74b89d2b9da5438d35d5ec7bb"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.api]
        url = "https://github.com/TeamPiped/Piped-Backend/archive/d149f88f1208934a21d0590bbabba25e4e50e448.tar.gz"
        sha256 = "0191936e3abe1fe3b9ee4309e8d63cd3ea2d6179d549a41917f5d1dba6c721ab"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/Piped-Backend/"

        [resources.sources.proxy]
        url = "https://github.com/TeamPiped/piped-proxy/archive/f86433dbadea493588ad9934fd89e9b9b24af8dc.tar.gz"
        sha256 = "5e67bac57c21e7ab88ec905361f8258fc1ffc6305e1acba0808a6bfed090f63e"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/piped-proxy/"

        [resources.sources.jdk]
        amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz"
        amd64.sha256 = "974d3acef0b7193f541acb61b76e81670890551366625d4f6ca01b91ac152ce0"
        arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.7_6.tar.gz"
        arm64.sha256 = "31dba70ba928c78c20d62049ac000f79f7a7ab11f9d9c11e703f52d60aa64f93"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
        autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
        autoupdate.asset.amd64 = "OpenJDK.*-jdk_x64_linux_hotspot_.*\\.tar\\.gz$"
        autoupdate.asset.arm64 = "OpenJDK.*-jdk_aarch64_linux_hotspot_.*\\.tar\\.gz$"

[resources.system_user]

[resources.install_dir]
group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

[resources.apt]
packages = "postgresql, build-essential"

[resources.database]
type = "postgresql"

[resources.ports]
    [resources.ports.proxy]
