#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "piped"
name = "Piped"

description.en = "Alternative front-end for YouTube"
description.fr = "Interface alternative pour YouTube"

version = "2026.01.24~ynh7"

maintainers = [ "orhtej2" ]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://docs.piped.video/"
demo = "https://piped.video/"
admindoc = "https://docs.piped.video/docs/"

code = "https://github.com/TeamPiped/Piped"

[integration]
yunohost = '>= 11.2'
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/TeamPiped/Piped/archive/c4e6f40ed38316755f80b8853a85ce73bcbf4037.tar.gz"
        sha256 = "05075d2c56d3564d9a51ecc196e07c666f34ba670e4e1e0730901ad1d657c885"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.npe]
        url = "https://github.com/TeamNewPipe/NewPipeExtractor/archive/refs/tags/v0.25.2.tar.gz"
        sha256 = "6a53a9624c450bd71dff44067370887af5af39a7c389969e329583050b675d8a"
        autoupdate.strategy = "latest_github_tag"
        autoupdate.upstream = "https://github.com/TeamNewPipe/NewPipeExtractor/"

        [resources.sources.api]
        url = "https://github.com/TeamPiped/Piped-Backend/archive/da5bcd76c82197491569c0df89bcdb4883c794e6.tar.gz"
        sha256 = "9ace9313a1eb33dd3a40b4d8ae378583c9efac0489fd81a91ee848e2a3b02e57"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/Piped-Backend/"

        [resources.sources.proxy]
        url = "https://github.com/TeamPiped/piped-proxy/archive/9c957f8d63eebe4d94810e7b0c5da3479e7cf535.tar.gz"
        sha256 = "ae27ace70dc2e5e6fff762b6e02dcdc7020c92fdc6f498c1e6ef0b2f4a072e16"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/piped-proxy/"

        [resources.sources.jdk]
        amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.10%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.10_7.tar.gz"
        amd64.sha256 = "ea3b9bd464d6dd253e9a7accf59f7ccd2a36e4aa69640b7251e3370caef896a4"
        arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.10%2B7/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.10_7.tar.gz"
        arm64.sha256 = "357fee29fb0d5c079f6730db98b28942df13a6eed426f6c61cd4ad703ab27b9a"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
        autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
        autoupdate.asset.amd64 = "OpenJDK.*-jdk_x64_linux_hotspot_.*\\.tar\\.gz$"
        autoupdate.asset.arm64 = "OpenJDK.*-jdk_aarch64_linux_hotspot_.*\\.tar\\.gz$"

[resources.system_user]

[resources.install_dir]
group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

[resources.apt]
packages = "postgresql, build-essential, libclang-dev"

[resources.database]
type = "postgresql"

[resources.ports]
    [resources.ports.proxy]

    [resources.nodejs]
    version = "20"
