#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "piped"
name = "Piped"

description.en = "Alternative front-end for YouTube"
description.fr = "Interface alternative pour YouTube"

version = "2026.05.04~ynh2"

maintainers = [ "orhtej2" ]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://docs.piped.video/"
demo = "https://piped.video/"
admindoc = "https://docs.piped.video/docs/"

code = "https://github.com/TeamPiped/Piped"

[integration]
yunohost = '>= 11.2'
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/TeamPiped/Piped/archive/da7ab357b4a75a4eaff068287f1563edd73ab862.tar.gz"
        sha256 = "5fa9f8a65467382a7b0f6cd0ec00e8da0fde2920d83586d8ee92e7cf73cc962d"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.api]
        url = "https://github.com/TeamPiped/Piped-Backend/archive/e3c7bdbb1e24ec27afe76e2f61b02d2dc662b49f.tar.gz"
        sha256 = "76612b438bddc434790b87be2c5ad1f5242c6e449bec4ed97b7b14b7d79d6195"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/Piped-Backend/"

        [resources.sources.proxy]
        url = "https://github.com/TeamPiped/piped-proxy/archive/fe25e12247a00cc6814e086c1447d5eb7b8ca0f3.tar.gz"
        sha256 = "c9ba1d564c0ab02d0ec88a2d6aa5d800c232afdee227a7616a51e4b0e9e8b801"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/piped-proxy/"

        [resources.sources.jdk]
        amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_x64_linux_hotspot_21.0.11_10.tar.gz"
        amd64.sha256 = "4b2220e232a97997b436ca6ab15cbf70171ecff52958a46159dfa5a8c44ca4de"
        arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.11_10.tar.gz"
        arm64.sha256 = "8d498ec88e1c1989fab95c6784240ab92d011e29c54d20a3f9c324b13476f9ad"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
        autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
        autoupdate.asset.amd64 = "OpenJDK.*-jdk_x64_linux_hotspot_.*\\.tar\\.gz$"
        autoupdate.asset.arm64 = "OpenJDK.*-jdk_aarch64_linux_hotspot_.*\\.tar\\.gz$"

[resources.system_user]

[resources.install_dir]
group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

[resources.apt]
packages = "postgresql, build-essential, libclang-dev"

[resources.database]
type = "postgresql"

[resources.ports]
    [resources.ports.proxy]

    [resources.nodejs]
    version = "20"
