#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "piped"
name = "Piped"

description.en = "An open-source alternative frontend for YouTube which is efficient by design."

version = "2024.03.07~ynh1"

maintainers = [ "orhtej2" ]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://docs.piped.video/"
demo = "https://piped.video/"
admindoc = "https://docs.piped.video/docs/"

code = "https://github.com/TeamPiped/Piped"

[integration]
yunohost = '>= 11.2'
architectures = [ "amd64", "arm64" ]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/TeamPiped/Piped/archive/7abab711c5a2bb183c792b430971c05bcc7312eb.tar.gz"
        sha256 = "2d3c69d91938fff01bb50afc8a2a25b53327d065dd20789b5badac8ab0afab5f"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.api]
        url = "https://github.com/TeamPiped/Piped-Backend/archive/32f8c9b6c48dfa3334a70ba42c2d687185d60390.tar.gz"
        sha256 = "0c3042de1a097d777721c968c56ed9c1e9602b4b215b963b7411962507392db2"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/Piped-Backend/"

        [resources.sources.proxy]
        url = "https://github.com/TeamPiped/piped-proxy/archive/d2513f125cb1f915a43733af57e8864f62350953.tar.gz"
        sha256 = "115428047f64bd8c79fd7aa7fb1116d9271705d669492d2440b88c7b943f0ca1"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/piped-proxy/"

        [resources.sources.jdk]
        amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz"
        amd64.sha256 = "454bebb2c9fe48d981341461ffb6bf1017c7b7c6e15c6b0c29b959194ba3aaa5"
        arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.2_13.tar.gz"
        arm64.sha256 = "3ce6a2b357e2ef45fd6b53d6587aa05bfec7771e7fb982f2c964f6b771b7526a"

[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"

[resources.apt]
packages = "postgresql"

[resources.database]
type = "postgresql"

[resources.ports]
    [resources.ports.proxy]
