#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "piped"
name = "Piped"

description.en = "Alternative front-end for YouTube"
description.fr = "Interface alternative pour YouTube"

version = "2026.04.06~ynh1"

maintainers = [ "orhtej2" ]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://docs.piped.video/"
demo = "https://piped.video/"
admindoc = "https://docs.piped.video/docs/"

code = "https://github.com/TeamPiped/Piped"

[integration]
yunohost = '>= 11.2'
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/TeamPiped/Piped/archive/17149cebfb511ded11a6f9090eff9cfc97290f96.tar.gz"
        sha256 = "c53d1c28e604aeaa26e570b6bd475aa7a30bd019f84020fb70a74da085136ca2"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.api]
        url = "https://github.com/TeamPiped/Piped-Backend/archive/e3c7bdbb1e24ec27afe76e2f61b02d2dc662b49f.tar.gz"
        sha256 = "76612b438bddc434790b87be2c5ad1f5242c6e449bec4ed97b7b14b7d79d6195"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/Piped-Backend/"

        [resources.sources.proxy]
        url = "https://github.com/TeamPiped/piped-proxy/archive/38f3eb3ce40eb17ac46f818b8e7b7c0b11ed833f.tar.gz"
        sha256 = "733433b2b2a64bef790cdf50490bfe95cef0871f9ba817aa3e97731b88d5938d"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.upstream = "https://github.com/TeamPiped/piped-proxy/"

        [resources.sources.jdk]
        amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.10%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.10_7.tar.gz"
        amd64.sha256 = "ea3b9bd464d6dd253e9a7accf59f7ccd2a36e4aa69640b7251e3370caef896a4"
        arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.10%2B7/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.10_7.tar.gz"
        arm64.sha256 = "357fee29fb0d5c079f6730db98b28942df13a6eed426f6c61cd4ad703ab27b9a"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
        autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
        autoupdate.asset.amd64 = "OpenJDK.*-jdk_x64_linux_hotspot_.*\\.tar\\.gz$"
        autoupdate.asset.arm64 = "OpenJDK.*-jdk_aarch64_linux_hotspot_.*\\.tar\\.gz$"

[resources.system_user]

[resources.install_dir]
group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

[resources.apt]
packages = "postgresql, build-essential, libclang-dev"

[resources.database]
type = "postgresql"

[resources.ports]
    [resources.ports.proxy]

    [resources.nodejs]
    version = "20"
