packaging_format = 2

id = "piped"
name = "Piped"

description.en = "An open-source alternative frontend for YouTube which is efficient by design."

version = "2024.01.29~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://docs.piped.video/"
demo = "https://piped.video/"
admindoc = "https://docs.piped.video/docs/"

code = "https://github.com/TeamPiped/Piped"

[integration]
yunohost = '>= 11.2'
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/TeamPiped/Piped/archive/564d59427e73dd455547ee4bea396f0ff2c6d965.tar.gz"
        sha256 = "983848b6596314e6340ad9bfcf9aa08d44bd2bc82f9c81e12e1b3445408d5264"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.api]
        url = "https://github.com/TeamPiped/Piped/archive/564d59427e73dd455547ee4bea396f0ff2c6d965.tar.gz"
        sha256 = "983848b6596314e6340ad9bfcf9aa08d44bd2bc82f9c81e12e1b3445408d5264"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.proxy]
        url = "https://github.com/TeamPiped/Piped/archive/564d59427e73dd455547ee4bea396f0ff2c6d965.tar.gz"
        sha256 = "983848b6596314e6340ad9bfcf9aa08d44bd2bc82f9c81e12e1b3445408d5264"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.jdk]
        amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz"
        amd64.sha256 = "454bebb2c9fe48d981341461ffb6bf1017c7b7c6e15c6b0c29b959194ba3aaa5"
        arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.2_13.tar.gz"
        arm64.sha256 = "3ce6a2b357e2ef45fd6b53d6587aa05bfec7771e7fb982f2c964f6b771b7526a"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"

    [resources.ports]
        [resources.ports.proxy]
