#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.48c0f45f5f0d67c2612211f6b0e7293e344d0639.name = "Upgrade from 2026.02.20~ynh2"
