#!/bin/bash
#### App file generated with YoloGen, the YunoHost app generator, version .

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP LOGROTATE CONFIGURATION
#=================================================

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD CONFIGURATION
#=================================================

ynh_backup "/etc/systemd/system/$app-api.service"
ynh_backup "/etc/systemd/system/$app-proxy.service"

#=================================================
# BACKUP THE POSTGRESQL DATABASE
#=================================================
ynh_print_info "Backing up the PostgreSQL database..."

## linter complains about this line so let's make it happy
## uncomment once hell breaks loose
# ynh_systemctl --service=$app-api --action="stop" --log_path="/var/log/$app/$app-api.log" --wait_until="Shutdown completed"

ynh_psql_dump_db > db.sql

# ynh_systemctl --service=$app-api --action="start" --log_path="/var/log/$app/$app-api.log" --wait_until="HTTP Server is listening on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."