#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#REMOVEME? ynh_nodejs_install

ynh_setup_source --dest_dir="$install_dir/jdk" --source_id="jdk"

ynh_hide_warnings ynh_exec_as_app RUSTUP_HOME="$install_dir"/.rustup CARGO_HOME="$install_dir"/.cargo bash -c 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y'
export PATH="$install_dir/jdk/bin:$install_dir/.cargo/bin:$PATH"

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

ynh_setup_source --dest_dir="$install_dir/build_api" --source_id="api"

ynh_setup_source --dest_dir="$install_dir/build_proxy" --source_id="proxy"

chown -R $app:www-data "$install_dir"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Building UI..."

pushd $install_dir/build
    corepack enable
    ynh_hide_warnings npm install -g corepack@latest
    ynh_hide_warnings corepack prepare  pnpm@latest --activate
    ynh_hide_warnings ynh_exec_as_app pnpm install
    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production pnpm build
    ynh_hide_warnings ynh_exec_as_app ./localizefonts.sh
popd

mv $install_dir/build/dist $install_dir
pushd $install_dir/dist
    sed -i s/pipedapi.kavin.rocks/"$domain\\/api"/g assets/*
popd
chown -R $app:www-data "$install_dir/dist"
chmod -R 755 "$install_dir/dist"

ynh_safe_rm "$install_dir/build"
ynh_safe_rm "$install_dir/.local"
ynh_safe_rm "$install_dir/.cache"

ynh_script_progression "Building API..."

pushd $install_dir/build_api
    ynh_hide_warnings ynh_exec_as_app JAVA_HOME=$install_dir/jdk ./gradlew shadowJar
    ynh_hide_warnings ynh_exec_as_app JAVA_HOME=$install_dir/jdk ./gradlew --stop
popd

mv $install_dir/build_api/build/libs/piped-1.0-all.jar $install_dir/piped.jar
ynh_config_add --template="config.properties" --destination="$install_dir/config.properties"
chmod 600 "$install_dir/config.properties"
ynh_safe_rm "$install_dir/.gradle"
ynh_safe_rm "$install_dir/build_api"

ynh_script_progression "Building Proxy..."

pushd $install_dir/build_proxy
    ynh_hide_warnings ynh_exec_as_app PATH=$PATH cargo build --release
popd

mv $install_dir/build_proxy/target/release/piped-proxy $install_dir
ynh_safe_rm "$install_dir/.rustup"
ynh_safe_rm "$install_dir/.cargo"
ynh_safe_rm "$install_dir/build_proxy"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

### systemd

mkdir -p "/var/log/$app"
touch "/var/log/$app/$app-api.log"
touch "/var/log/$app/$app-proxy.log"

ynh_config_add_logrotate "/var/log/$app/$app-api.log"
ynh_config_add_logrotate "/var/log/$app/$app-proxy.log"

ynh_config_add_systemd --template="api.service" --service="$app-api"
yunohost service add "$app-api" --description="Piped backend API service" --log="/var/log/$app/$app-api.log"

ynh_config_add_systemd --template="proxy.service" --service="$app-proxy"
yunohost service add "$app-proxy" --description="Piped HTTP proxy service" --log="/var/log/$app/$app-proxy.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app-api --action="start" --log_path="/var/log/$app/$app-api.log" --wait_until="Database connection is ready!"

ynh_systemctl --service=$app-proxy --action="start" --log_path="/var/log/$app/$app-proxy.log" --wait_until="Running server!"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
