#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app-api >/dev/null
then
    ynh_script_progression --message="Removing $app-api service integration..."
    ynh_remove_systemd_config --service="$app-api"
    yunohost service remove $app-api
fi

if ynh_exec_warn_less yunohost service status $app-proxy >/dev/null
then
    ynh_script_progression --message="Removing $app-proxy service integration..."
    ynh_remove_systemd_config --service="$app-proxy"
    yunohost service remove $app-proxy
fi

ynh_remove_nginx_config

# Remove other various files specific to the app... such as :

ynh_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last