#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app-api >/dev/null
then
    ynh_script_progression "Removing $app-api service integration..."
    ynh_config_remove_systemd"$app-api"
    yunohost service remove $app-api
fi

if ynh_hide_warnings yunohost service status $app-proxy >/dev/null
then
    ynh_script_progression "Removing $app-proxy service integration..."
    ynh_config_remove_systemd"$app-proxy"
    yunohost service remove $app-proxy
fi

ynh_config_remove_nginx

# Remove other various files specific to the app... such as :

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
